### ISSUE TITLE
ERROR: linux-lx2k-5.4-r0 do_compile: oe_runmake failed

### ISSUE THREAD

**Issue by outbackdingo** [jonmason/meta-lx2k#1]
Build Configuration:
BB_VERSION           = "1.47.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "fedora-32"
TARGET_SYS           = "aarch64-overc-linux"
MACHINE              = "honeycomb_lx2k"
DISTRO               = "overc"
DISTRO_VERSION       = "1.0"
TUNE_FEATURES        = "aarch64"
TARGET_FPU           = ""
meta                 
meta-poky            
meta-yocto-bsp       = "master:52276e385d0c80c3e6f2a3f142289dc09697556f"
meta-oe              
meta-python          
meta-networking      
meta-filesystems     
meta-multimedia      
meta-perl            = "master:2258c9a767391e4529665cd6508e4b32bd18d130"
meta-overc           
meta-cube            = "master:264d1d0949fb5e9ec8e39b1f7604086d59ec2047"
meta-intel           = "master:a064295cd5e40f83e86378f86dd42d7f783a6eea"
meta-arm             
meta-arm-toolchain   = "master:a7dc1671044ce2b5a85957225e54f04232e42ce0"
meta-kernel          = "master:e72835dcab0f3d611929a6de43d351179c05d453"
meta-lx2k            = "master:23d94101ab9bd35a5cac2b0d204ee1d18bbd40f6"
meta-virtualization  = "master:7a8167fa82621dd606260450b1e648e50a1d79ab"
meta-cloud-services  = "master:4f6cd1d6664ca1a51bdc742291fe4bf83ecf2a92"
meta-security        = "master:4c2f7ffd492c7083273aca7cc718802279f05ce2"
meta-selinux         = "master:6e1100d29aec118df2025c46c77f4c8aa8da4e76"
meta-gnome           
meta-xfce            = "master:2258c9a767391e4529665cd6508e4b32bd18d130"
meta-awnix           = "master:c616414c6ed4f6f2ab75703ce5a3e84acacd3c47"
workspace            = "master:32f1010ad0d36b886ecde57290061558fc22929a"

WARNING: linux-lx2k-5.4-r0 do_kernel_configcheck: [kernel config]: specified values did not make it into the kernel's final configuration:

    [NOTE]: 'CONFIG_GCC_VERSION' last val (80300) and .config val (100200) do not match
    [INFO]: CONFIG_GCC_VERSION : 100200 ## .config: 9 :configs//./defconfig (80300) 
    [INFO]: raw config text:

        config GCC_VERSION
        	int
        	default 100200 if CC_IS_GCC
        	default 0

    [INFO]: config 'CONFIG_GCC_VERSION' was set, but it wasn't assignable, check (parent) dependencies
    [NOTE]: 'CONFIG_LOCALVERSION' last val ("") and .config val ("-yocto-standard") do not match
    [INFO]: CONFIG_LOCALVERSION : "-yocto-standard" ## .config: 25 :configs//./defconfig ("") 
    [INFO]: raw config text:

        config LOCALVERSION
        	string "Local version - append to kernel release"
        	help
        	  Append an extra string to the end of your kernel version.
        	  This will show up when you type uname, for example.
        	  The string you set here will be appended after the contents of
        	  any files with a filename matching localversion* in your
        	  object and source tree, in that order.  Your total string can
        	  be a maximum of 64 characters.

    [INFO]: config 'CONFIG_LOCALVERSION' was set, but it wasn't assignable, check (parent) dependencies

ERROR: linux-lx2k-5.4-r0 do_compile: oe_runmake failed
ERROR: linux-lx2k-5.4-r0 do_compile: Execution of '/var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/temp/run.do_compile.2498606' failed with exit code 1:
  GEN     Makefile
  HOSTLD  scripts/dtc/dtc
/var/home/dingo/overc/honeycomb/tmp/hosttools/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x20): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [scripts/Makefile.host:116: scripts/dtc/dtc] Error 1
make[1]: *** [/var/home/dingo/overc/honeycomb/tmp/work-shared/honeycomb_lx2k/kernel-source/Makefile:1263: scripts_dtc] Error 2
make: *** [/var/home/dingo/overc/honeycomb/tmp/work-shared/honeycomb_lx2k/kernel-source/Makefile:179: sub-make] Error 2
WARNING: /var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/temp/run.do_compile.2498606:302 exit 1 from 'exit 1'
WARNING: Backtrace (BB generated script): 
	#1: bbfatal_log, /var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/temp/run.do_compile.2498606, line 302
	#2: die, /var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/temp/run.do_compile.2498606, line 282
	#3: oe_runmake, /var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/temp/run.do_compile.2498606, line 209
	#4: kernel_do_compile, /var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/temp/run.do_compile.2498606, line 198
	#5: do_compile, /var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/temp/run.do_compile.2498606, line 148
	#6: main, /var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/temp/run.do_compile.2498606, line 306

Backtrace (metadata-relative locations):
	#1: bbfatal_log, /var/home/dingo/overc/poky/meta/classes/logging.bbclass, line 72
	#2: die, /var/home/dingo/overc/poky/meta/classes/base.bbclass, line 56
	#3: oe_runmake, /var/home/dingo/overc/poky/meta/classes/base.bbclass, line 65
	#4: kernel_do_compile, /var/home/dingo/overc/poky/meta/classes/kernel.bbclass, line 349
	#5: do_compile, autogenerated, line 2
ERROR: Logfile of failure stored in: /var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/temp/log.do_compile.2498606
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 16 HOSTCC=gcc  -isystem/var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/recipe-sysroot-native/usr/include -O2 -pipe -L/var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/recipe-sysroot-native/usr/lib                         -L/var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/recipe-sysroot-native/lib                         -Wl,--enable-new-dtags                         -Wl,-rpath-link,/var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/recipe-sysroot-native/usr/lib                         -Wl,-rpath-link,/var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/recipe-sysroot-native/lib                         -Wl,-rpath,/var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/recipe-sysroot-native/usr/lib                         -Wl,-rpath,/var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/recipe-sysroot-native/lib                         -Wl,-O1 HOSTCPP=gcc  -E HOSTCXX=g++  -isystem/var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/recipe-sysroot-native/usr/include -O2 -pipe -L/var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/recipe-sysroot-native/usr/lib                         -L/var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/recipe-sysroot-native/lib                         -Wl,--enable-new-dtags                         -Wl,-rpath-link,/var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/recipe-sysroot-native/usr/lib                         -Wl,-rpath-link,/var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/recipe-sysroot-native/lib                         -Wl,-rpath,/var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/recipe-sysroot-native/usr/lib                         -Wl,-rpath,/var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/recipe-sysroot-native/lib                         -Wl,-O1 Image.gz CC=aarch64-overc-linux-gcc   -fuse-ld=bfd -fmacro-prefix-map=/var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0=/usr/src/debug/linux-lx2k/5.4-r0                      -fdebug-prefix-map=/var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0=/usr/src/debug/linux-lx2k/5.4-r0                      -fdebug-prefix-map=/var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/recipe-sysroot=                      -fdebug-prefix-map=/var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/recipe-sysroot-native=  -fdebug-prefix-map=/var/home/dingo/overc/honeycomb/tmp/work-shared/honeycomb_lx2k/kernel-source=/usr/src/kernel  --sysroot=/var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/recipe-sysroot   LD=aarch64-overc-linux-ld.bfd    --sysroot=/var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/recipe-sysroot
|   GEN     Makefile
|   HOSTLD  scripts/dtc/dtc
| /var/home/dingo/overc/honeycomb/tmp/hosttools/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x20): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here
| collect2: error: ld returned 1 exit status
| make[2]: *** [scripts/Makefile.host:116: scripts/dtc/dtc] Error 1
| make[1]: *** [/var/home/dingo/overc/honeycomb/tmp/work-shared/honeycomb_lx2k/kernel-source/Makefile:1263: scripts_dtc] Error 2
| make: *** [/var/home/dingo/overc/honeycomb/tmp/work-shared/honeycomb_lx2k/kernel-source/Makefile:179: sub-make] Error 2
| ERROR: oe_runmake failed
| WARNING: /var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/temp/run.do_compile.2498606:302 exit 1 from 'exit 1'
| WARNING: Backtrace (BB generated script):
| 	#1: bbfatal_log, /var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/temp/run.do_compile.2498606, line 302
| 	#2: die, /var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/temp/run.do_compile.2498606, line 282
| 	#3: oe_runmake, /var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/temp/run.do_compile.2498606, line 209
| 	#4: kernel_do_compile, /var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/temp/run.do_compile.2498606, line 198
| 	#5: do_compile, /var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/temp/run.do_compile.2498606, line 148
| 	#6: main, /var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/temp/run.do_compile.2498606, line 306
| ERROR: Execution of '/var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/temp/run.do_compile.2498606' failed with exit code 1:
|   GEN     Makefile
|   HOSTLD  scripts/dtc/dtc
| /var/home/dingo/overc/honeycomb/tmp/hosttools/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x20): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here
| collect2: error: ld returned 1 exit status
| make[2]: *** [scripts/Makefile.host:116: scripts/dtc/dtc] Error 1
| make[1]: *** [/var/home/dingo/overc/honeycomb/tmp/work-shared/honeycomb_lx2k/kernel-source/Makefile:1263: scripts_dtc] Error 2
| make: *** [/var/home/dingo/overc/honeycomb/tmp/work-shared/honeycomb_lx2k/kernel-source/Makefile:179: sub-make] Error 2
| WARNING: /var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/temp/run.do_compile.2498606:302 exit 1 from 'exit 1'
| WARNING: Backtrace (BB generated script):
| 	#1: bbfatal_log, /var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/temp/run.do_compile.2498606, line 302
| 	#2: die, /var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/temp/run.do_compile.2498606, line 282
| 	#3: oe_runmake, /var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/temp/run.do_compile.2498606, line 209
| 	#4: kernel_do_compile, /var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/temp/run.do_compile.2498606, line 198
| 	#5: do_compile, /var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/temp/run.do_compile.2498606, line 148
| 	#6: main, /var/home/dingo/overc/honeycomb/tmp/work/honeycomb_lx2k-overc-linux/linux-lx2k/5.4-r0/temp/run.do_compile.2498606, line 306
| 
| Backtrace (metadata-relative locations):
| 	#1: bbfatal_log, /var/home/dingo/overc/poky/meta/classes/logging.bbclass, line 72
| 	#2: die, /var/home/dingo/overc/poky/meta/classes/base.bbclass, line 56
| 	#3: oe_runmake, /var/home/dingo/overc/poky/meta/classes/base.bbclass, line 65
| 	#4: kernel_do_compile, /var/home/dingo/overc/poky/meta/classes/kernel.bbclass, line 349
| 	#5: do_compile, autogenerated, line 2
ERROR: Task (/var/home/dingo/overc/meta-lx2k/recipes-kernel/linux/linux-lx2k_5.4.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2341 tasks of which 2318 didn't need to be rerun and 1 failed.

**Comment by jonmason** [comment]
Unable to reproduce on Debian 10.  I pushed a number of fixes recently.  None of which seem like it would correct this issue, but would be nice to verify it is still a problem.

**Comment by outbackdingo** [comment]
caused by a gcc 10.2 issue on fedora build hosts, using u-boot 2020_04 fixes it as opposed to 2019_10 which is what solidrun uses.
