### ISSUE TITLE
trusted-firmware-a-1.5-r0 do_install: Unsupported TFA_INSTALL_TARGET target pbl

### ISSUE THREAD

**Issue by outbackdingo** [jonmason/meta-lx2k#2]
ERROR: trusted-firmware-a-1.5-r0 do_install: Unsupported TFA_INSTALL_TARGET target pbl
ERROR: trusted-firmware-a-1.5-r0 do_install: Execution of '/home/dingo/overc/lx2k/tmp/work/honeycomb_lx2k-poky-linux/trusted-firmware-a/1.5-r0/temp/run.do_install.8399' failed with exit code 1:
Install fip.bin
WARNING: exit code 1 from a shell command.

ERROR: Logfile of failure stored in: /home/dingo/overc/lx2k/tmp/work/honeycomb_lx2k-poky-linux/trusted-firmware-a/1.5-r0/temp/log.do_install.8399
ERROR: Task (/home/dingo/overc/meta-arm/meta-arm/recipes-bsp/trusted-firmware-a/trusted-firmware-a_1.5.bb:do_install) failed with exit code '1'

**Comment by jonmason** [comment]
Fixed in commit 5cffa0a89fc8d91dc961a788069572b2e4119be1
